# Config file for ShapeSet generator

input_folder: './shapes'
output_folder: 'output'

# how many samples per shape
sample_size: 5

# width and height of output
width: 256
height: 256

shapes: [] # empty array == all shapes

# other params
noise: 99 # 0-255
angle: 40