# Config file for ShapeSet generator

input_folder: './shapes'
output_folder: 'output'

# how many samples per shape
sample_size: 10

# width and height of output
width: 256
height: 256

shapes: [] # empty array == all shapes

# other params
noise: 40 # 0-255
angle: 360
translation: 0.5
scale: 0.6